# Generated by Django 3.2.5 on 2021-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
